services:
  comfybot:
    build: .
    container_name: comfybot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=8408589933:AAGcfOlpwJ3y5kX11GDEpopuIiCEx_XNRKQ
      - COMFYUI_HOST=host.docker.internal:7860
    volumes:
      - ./zimage.json:/app/zimage.json:ro
